// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7w3AimKvhNQygAijpdB7ms
// Component: NsUGHpG-oO9I
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Navbar from "../../Navbar"; // plasmic-import: yZ_cQNVr9Dd_/component
import ServiceWhite from "../../ServiceWhite"; // plasmic-import: Qe_Hmrr_jlV3/component
import ServiceDark from "../../ServiceDark"; // plasmic-import: TurYmfwZ9Nwp/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: SSIvXflUB2k5/component
import FooterMain from "../../FooterMain"; // plasmic-import: 3Hx5Xex_O1aO/component
import { useScreenVariants as useScreenVariantsnU8IdsSvi2F6 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nU8idsSVI2F6/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import * as projectcss from "./plasmic.module.css"; // plasmic-import: 7w3AimKvhNQygAijpdB7ms/projectcss
import * as sty from "./PlasmicServices.module.css"; // plasmic-import: NsUGHpG-oO9I/css

createPlasmicElementProxy;

export const PlasmicServices__VariantProps = new Array();

export const PlasmicServices__ArgProps = new Array();

const $$ = {};

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicServices.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicServices.pageMetadata.title}
      />

      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicServices.pageMetadata.title}
      />
    </>
  );
}

function PlasmicServices__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnU8IdsSvi2F6()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div
            data-plasmic-name={"verticalStack"}
            data-plasmic-override={overrides.verticalStack}
            className={classNames(projectcss.all, sty.verticalStack)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__m9FbW)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Comprehensive Financial Solutions Tailored to Your Needs"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fpoZ
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "At Ackrell Capital Industrial Bank, we offer a wide range of services designed to support the financial growth and stability of businesses across industries. Our innovative and reliable solutions are tailored to meet the unique needs of our clients, ensuring that you have the tools and resources necessary to achieve your financial goals."
                    : "At Ackrell Capital Industrial Bank, we offer a wide range of services designed to support the financial growth and stability of businesses across industries. Our innovative and reliable solutions are tailored to meet the unique needs of our clients, ensuring that you have the tools and resources necessary to achieve your financial goals."}
                </div>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xrZUp)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sz8Hm)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__v7PO0)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__keVsY)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___7Qruh
                    )}
                  >
                    {"Personal & Business Banking"}
                  </h2>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__qy59
                    )}
                  >
                    {"Streamline Your Financial Operations"}
                  </h6>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___73P1J
                    )}
                  >
                    {
                      "Our business banking services are designed to simplify and enhance your financial operations, providing you with the support you need to focus on what matters most\u2014growing your business."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ziPpJ)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__mDxxc)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__b2Skn
                        )}
                        slot2={
                          "Manage your business finances with ease through our versatile checking and savings accounts."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___5Qaoq
                          )}
                        >
                          {"Business Checking and Savings Accounts"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__idGmw)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__qlUrm
                        )}
                        slot2={
                          "Access the capital you need for expansion, equipment purchases, and other business investments."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__xZMv
                          )}
                        >
                          {"Commercial Loans and Lines of Credit"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__seYey)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__ddVd
                        )}
                        slot2={
                          "Optimize your cash flow and manage liquidity with our advanced treasury solutions."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__kg27N
                          )}
                        >
                          {"Treasury and Cash Management"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__dAnAk)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__iiZIk
                        )}
                        slot2={
                          "Enhance your payment processing capabilities with our comprehensive merchant services, including POS systems and online payment gateways."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__gAp2R
                          )}
                        >
                          {"Merchant Services"}
                        </h3>
                      </ServiceWhite>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___3Hb5U)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___6HWsK)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__rnCU)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___8Ov2G)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__wH1Mn
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Service category"
                      : "Commercial Lending"}
                  </h2>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__dt2N
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile") ? (
                      "Service category"
                    ) : (
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h6
                            className={classNames(
                              projectcss.all,
                              projectcss.h6,
                              projectcss.__wab_text,
                              sty.h6__romJ
                            )}
                          >
                            {"Empowering Your Business Growth"}
                          </h6>
                        }

                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    )}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c7E4H
                    )}
                  >
                    {
                      "Our commercial lending solutions provide the financial support your business needs to thrive in a competitive market. We offer a range of loan products with flexible terms and competitive rates."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zWaZv)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow2"}
                    data-plasmic-override={overrides.serviceRow2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___8Ue0W)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__yfsZz
                        )}
                        slot={
                          "Finance long-term projects or capital expenditures with our fixed-term loans."
                        }
                      >
                        {"Term Loans"}
                      </ServiceDark>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__tqcUu)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__sjaFl
                        )}
                        slot={
                          "Obtain the machinery and equipment you need to grow your operations."
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hmsHu
                          )}
                        >
                          {"Equipment Financing"}
                        </div>
                      </ServiceDark>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ys6WI)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__yw5Vh
                        )}
                        slot={
                          "Invest in commercial real estate with confidence through our tailored financing options."
                        }
                      >
                        {"Real Estate Loans"}
                      </ServiceDark>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__vc4Rx)}
                    >
                      <ServiceDark
                        className={classNames(
                          "__wab_instance",
                          sty.serviceDark__sw5V3
                        )}
                        slot={
                          "Maintain liquidity and manage day-to-day operations with our working capital solutions."
                        }
                      >
                        {"Working Capital Loans"}
                      </ServiceDark>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__e8G0Y)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__g8MJw)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uhZq3)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hG0IQ)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__fuq70
                    )}
                  >
                    {"Treasury and Cash Management"}
                  </h2>
                  <h6
                    className={classNames(
                      projectcss.all,
                      projectcss.h6,
                      projectcss.__wab_text,
                      sty.h6__v4Bfh
                    )}
                  >
                    {"Optimize Your Cash Flow"}
                  </h6>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9U0PF
                    )}
                  >
                    {
                      "Our treasury and cash management services are designed to help you maximize your business's financial health. From liquidity management to fraud protection, we offer the tools and expertise you need."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xmXdh)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow3"}
                    data-plasmic-override={overrides.serviceRow3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___1Ry2L)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__k37Q3
                        )}
                        slot2={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c7Ofq
                            )}
                          >
                            {
                              "Optimize your cash position with our comprehensive liquidity solutions."
                            }
                          </div>
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__dd5Ob
                          )}
                        >
                          {"Liquidity Management"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ztHZg)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__f1CEy
                        )}
                        slot2={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cFvHk
                            )}
                          >
                            {
                              "Streamline your accounts receivable and payable processes for greater efficiency."
                            }
                          </div>
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___3Jp0T
                          )}
                        >
                          {"Receivables and Payables"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ab52C)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__gje5Z
                        )}
                        slot2={
                          "Safeguard your business from fraud with our advanced security measures and monitoring services."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__gAQx
                          )}
                        >
                          {"Fraud Protection"}
                        </h3>
                      </ServiceWhite>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__cvyzM)}
                    >
                      <ServiceWhite
                        className={classNames(
                          "__wab_instance",
                          sty.serviceWhite__co7O9
                        )}
                        slot2={
                          "Access real-time data and detailed reports to make informed financial decisions."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__kbZwy
                          )}
                        >
                          {"Information Reporting"}
                        </h3>
                      </ServiceWhite>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div
            data-plasmic-name={"footerTopSection"}
            data-plasmic-override={overrides.footerTopSection}
            className={classNames(projectcss.all, sty.footerTopSection)}
          >
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "verticalStack",
    "foreground2",
    "h1",
    "serviceRow",
    "serviceRow2",
    "serviceRow3",
    "footerTopSection",
    "homeFooterTop",
    "footerMain"
  ],

  navbar: ["navbar"],
  verticalStack: ["verticalStack", "foreground2", "h1"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  serviceRow: ["serviceRow"],
  serviceRow2: ["serviceRow2"],
  serviceRow3: ["serviceRow3"],
  footerTopSection: ["footerTopSection", "homeFooterTop"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicServices__ArgProps,
          internalVariantPropNames: PlasmicServices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicServices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServices";
  } else {
    func.displayName = `PlasmicServices.${nodeName}`;
  }
  return func;
}

export const PlasmicServices = Object.assign(
  // Top-level PlasmicServices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    verticalStack: makeNodeComponent("verticalStack"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    serviceRow: makeNodeComponent("serviceRow"),
    serviceRow2: makeNodeComponent("serviceRow2"),
    serviceRow3: makeNodeComponent("serviceRow3"),
    footerTopSection: makeNodeComponent("footerTopSection"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),
    // Metadata about props expected for PlasmicServices
    internalVariantProps: PlasmicServices__VariantProps,
    internalArgProps: PlasmicServices__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Service",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicServices;
/* prettier-ignore-end */
