// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7w3AimKvhNQygAijpdB7ms
// Component: yq_sh5_l5COL
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Navbar from "../../Navbar"; // plasmic-import: yZ_cQNVr9Dd_/component
import Button from "../../Button"; // plasmic-import: XhHp-qufC92V/component
import ServiceValue from "../../ServiceValue"; // plasmic-import: dJL4NKbYi32E/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: SSIvXflUB2k5/component
import FooterMain from "../../FooterMain"; // plasmic-import: 3Hx5Xex_O1aO/component
import { useScreenVariants as useScreenVariantsnU8IdsSvi2F6 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: nU8idsSVI2F6/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import * as projectcss from "./plasmic.module.css"; // plasmic-import: 7w3AimKvhNQygAijpdB7ms/projectcss
import * as sty from "./PlasmicAboutUs.module.css"; // plasmic-import: yq_sh5_l5COL/css
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 13gtm4V3y2AB/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 5Ji1vGCP__gF/icon

createPlasmicElementProxy;

export const PlasmicAboutUs__VariantProps = new Array();

export const PlasmicAboutUs__ArgProps = new Array();

const $$ = {};

export function Head() {
  return (
    <>
      <meta name="twitter:card" content="summary" />
      <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
      <meta
        key="og:title"
        property="og:title"
        content={PlasmicAboutUs.pageMetadata.title}
      />

      <meta
        key="twitter:title"
        name="twitter:title"
        content={PlasmicAboutUs.pageMetadata.title}
      />
    </>
  );
}

function PlasmicAboutUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnU8IdsSvi2F6()
  });
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__uhA7T)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile") ? (
                    "About US"
                  ) : (
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#FFFFFF" }}
                      >
                        {"About Us"}
                      </span>
                    </React.Fragment>
                  )}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__dJnNk
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile") ? (
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h5
                          data-plasmic-name={"h5"}
                          data-plasmic-override={overrides.h5}
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobile") ? (
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{
                                  color: "var(--token-jgohepLVeKvh)",
                                  fontWeight: 400
                                }}
                              >
                                {
                                  "Ackrell Capital Industrial Bank is a premier financial institution dedicated to providing innovative and reliable banking solutions. With a rich history of excellence and a forward-thinking approach, we are committed to supporting our clients' financial success and fostering long-term relationships built on trust and integrity."
                                }
                              </span>
                            </React.Fragment>
                          ) : (
                            <React.Fragment>
                              <span
                                className={
                                  "plasmic_default__all plasmic_default__span"
                                }
                                style={{ color: "var(--token-jgohepLVeKvh)" }}
                              >
                                {
                                  "Ackrell Capital Industrial                   Bank is a premier financial institution dedicated to providing innovative and reliable banking solutions. With a rich history of excellence and a forward-thinking approach, we are committed to supporting our clients' financial success and fostering long-term relationships built on trust and integrity."
                                }
                              </span>
                            </React.Fragment>
                          )}
                        </h5>
                      }

                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  ) : (
                    "Ackrell Capital Industrial Bank is a premier financial institution dedicated to providing innovative and reliable banking solutions. With a rich history of excellence and a forward-thinking approach, we are committed to supporting our clients' financial success and fostering long-term relationships built on trust and integrity."
                  )}
                </div>
              </Stack__>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__oh70J)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__jCcGk)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__m5Rnr)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"copy2"}
                    data-plasmic-override={overrides.copy2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.copy2)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__eMq9Z)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ks5K
                        )}
                      >
                        {"Our Mission"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__v8Gl
                        )}
                      >
                        {
                          "Our mission is to empower individuals, businesses, and communities by delivering comprehensive financial services that drive growth and prosperity. We strive to offer personalized solutions, exceptional customer service, and cutting-edge technology to meet the evolving needs of our clients."
                        }
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__eCp4C)}
                    >
                      <Button
                        data-plasmic-name={"button"}
                        data-plasmic-override={overrides.button}
                        className={classNames("__wab_instance", sty.button)}
                        color={"unnamedVariant"}
                        endIcon={
                          <Icon4Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rg644
                            )}
                            role={"img"}
                          />
                        }
                        link={"/user/register"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sxwt2
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___29Sfv
                          )}
                        >
                          {"Get Started"}
                        </div>
                      </Button>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox___6T67H)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__gYrXo)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___7FLi)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kq8W7)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__iEhmn
                    )}
                  >
                    {"Our values"}
                  </h2>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__szKeF)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__gkGdy)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__zqWwR
                        )}
                        slot={
                          "We adhere to the highest standards of ethics and transparency in all our dealings."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__neWyO
                          )}
                        >
                          {"Integrity"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__tvJdu)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__wgAal
                        )}
                        slot={
                          "We embrace technology and continuously seek new ways to improve our services."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__f9Qim
                          )}
                        >
                          {"Innovation"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__fdHfx)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue___1RtUw
                        )}
                        slot={
                          "Our clients' needs are at the forefront of everything we do."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__cJXmB
                          )}
                        >
                          {"Customer Focus"}
                        </h3>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hl4Z7
                          )}
                        >
                          {""}
                        </div>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___0KklI)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__tFlgl
                        )}
                        slot={
                          "We are committed to excellence in every aspect of our business."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__uDcZw
                          )}
                        >
                          {"Excellence"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hzfrl)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__epD2G
                        )}
                        slot={
                          "We believe in giving back and supporting the communities we serve."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__mqNl9
                          )}
                        >
                          {"Community"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sarU5)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__pzXdG
                        )}
                        slot={
                          "We foster a culture of teamwork and partnership to achieve shared success."
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__bosb6
                          )}
                        >
                          {"Collaboration"}
                        </h3>
                      </ServiceValue>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__epkIn)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__amIp7)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"copy"}
                data-plasmic-override={overrides.copy}
                hasGap={true}
                className={classNames(projectcss.all, sty.copy)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__p5HeL)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dKIkJ
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile") ? (
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__gxVv4
                            )}
                          >
                            {"Our History"}
                          </h2>
                        }

                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    ) : (
                      "Our History"
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6DiLb
                    )}
                  >
                    {
                      "Founded in 2003, Ackrell Capital Industrial Bank has grown from a small regional bank to a trusted financial partner with a broad network of branches and ATMs. Our journey is marked by a commitment to innovation and an unwavering dedication to our clients' financial well-being."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__pdl3Z)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__jQlUs)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"copy3"}
                data-plasmic-override={overrides.copy3}
                hasGap={true}
                className={classNames(projectcss.all, sty.copy3)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gUoz)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8TKuk
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile") ? (
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2___4Ai5O
                            )}
                          >
                            {"Leadership Team"}
                          </h2>
                        }

                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    ) : (
                      "Leadership Team"
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yp4G
                    )}
                  >
                    {
                      "Our leadership team comprises seasoned professionals with extensive experience in the banking and financial services industry. Their vision and expertise drive our strategic direction and ensure that we remain at the forefront of the industry."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__tHy86)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__rMUhF)}>
              <Stack__
                as={"div"}
                data-plasmic-name={"copy4"}
                data-plasmic-override={overrides.copy4}
                hasGap={true}
                className={classNames(projectcss.all, sty.copy4)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gVmhR)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0Q5A
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile") ? (
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__yBgW
                            )}
                          >
                            {"Corporate Responsibility"}
                          </h2>
                        }

                        <React.Fragment>{""}</React.Fragment>
                      </React.Fragment>
                    ) : (
                      "Corporate Responsibility"
                    )}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aFanc
                    )}
                  >
                    {
                      "At Ackrell Capital Industrial Bank, we believe in making a positive impact beyond banking. Our corporate responsibility initiatives focus on sustainability, financial literacy, and community engagement. We are dedicated to creating a better future for all."
                    }
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </Stack__>
          <div className={classNames(projectcss.all, sty.freeBox__rYcMj)}>
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "aboutUsBanner",
    "foreground2",
    "h1",
    "h5",
    "columns",
    "copy2",
    "button",
    "serviceRow",
    "copy",
    "copy3",
    "copy4",
    "homeFooterTop",
    "footerMain"
  ],

  navbar: ["navbar"],
  aboutUsBanner: ["aboutUsBanner", "foreground2", "h1", "h5"],
  foreground2: ["foreground2", "h1", "h5"],
  h1: ["h1"],
  h5: ["h5"],
  columns: ["columns", "copy2", "button"],
  copy2: ["copy2", "button"],
  button: ["button"],
  serviceRow: ["serviceRow"],
  copy: ["copy"],
  copy3: ["copy3"],
  copy4: ["copy4"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    h5: makeNodeComponent("h5"),
    columns: makeNodeComponent("columns"),
    copy2: makeNodeComponent("copy2"),
    button: makeNodeComponent("button"),
    serviceRow: makeNodeComponent("serviceRow"),
    copy: makeNodeComponent("copy"),
    copy3: makeNodeComponent("copy3"),
    copy4: makeNodeComponent("copy4"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),
    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "About Us",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
